-- SQLite
CREATE TABLE authors (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(25) NOT NULL
);


CREATE TABLE books (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(25) NOT NULL,
	author_id INTEGER REFERENCES authors(id)
);


CREATE TABLE customers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(25) NOT NULL,
	email VARCHAR(254) NOT NULL
	
);


CREATE TABLE rents (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	book_id INTEGER REFERENCES books(id),
	customer_id INTEGER REFERENCES customers(id),
	state VARCHAR(10) NOT NULL
);




